blog/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
    re_path(r'^$', views.post_list, name='post_list'),
    re_path(r'^post/(?P<slug>[\w\-]+)$', views.PostView.as_view(), name='post'),
]

homepage/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^bio', views.bio, name='bio'),
    re_path(r'^send_email', views.send_email, name='send_email'),
]

personal_site/urls.py
from django.conf import settings
from django.urls import include, re_path
from django.contrib.staticfiles.urls import static
from django.contrib import admin

urlpatterns = [
    re_path(r'^', include(('homepage.urls', 'homepage'), namespace='homepage')),
    re_path(r'^blog/', include(('blog.urls', 'blog'), namespace='blog')),
    re_path(r'^admin/', admin.site.urls)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
    re_path(r'^$', views.splash_page, name='splash'),
    # url(r'^post/(?P<slug>[\w\-]+)$', views.PostView.as_view(), name='post'),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.template.defaultfilters import slugify

import re
import string


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.PROTECT)
    title = models.CharField(max_length=200)
    text = models.TextField()
    slug = models.SlugField(unique=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_date']

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def has_been_modified(self):
        return self.created_date != self.modified_date

    def save(self, **kwargs):
        slug_str = '%s' % self.title
        unique_slugify(self, slug_str.lower())
        super(Post, self).save(**kwargs)

    def short_description(self, max_length=250):
            """Returns the beginning of the post's descriptions."""
            if len(self.text) <= max_length:
                return self.text
            s = ''
            d = self.text.split()
            while len(s) < max_length and len(d) > 0:
                s += d.pop(0) + ' '
            s = s.strip() + '...'
            return s

    def get_absolute_url(self):
        return reverse('blog:posts', args=[self.slug])

    def __str__(self):
        return self.title


def unique_slugify(instance, value, slug_field_name='slug', queryset=None,
                   slug_separator='-'):
    """
    Calculates and stores a unique slug of ``value`` for an instance.

    ``slug_field_name`` should be a string matching the name of the field to
    store the slug in (and the field to check against for uniqueness).

    ``queryset`` usually doesn't need to be explicitly provided - it'll default
    to using the ``.all()`` queryset from the model's default manager.
    """
    slug_field = instance._meta.get_field(slug_field_name)

    slug = getattr(instance, slug_field.attname)
    slug_len = slug_field.max_length

    # Sort out the initial slug, limiting its length if necessary.
    slug = slugify(value)
    if slug_len:
        slug = slug[:slug_len]
    slug = _slug_strip(slug, slug_separator)
    original_slug = slug

    # Create the queryset if one wasn't explicitly provided and exclude the
    # current instance from the queryset.
    if queryset is None:
        queryset = instance.__class__._default_manager.all()
    if instance.pk:
        queryset = queryset.exclude(pk=instance.pk)

    # Find a unique slug. If one matches, at '-2' to the end and try again
    # (then '-3', etc).
    next = 2
    while not slug or queryset.filter(**{slug_field_name: slug}):
        slug = original_slug
        end = '%s%s' % (slug_separator, next)
        if slug_len and len(slug) + len(end) > slug_len:
            slug = slug[:slug_len-len(end)]
            slug = _slug_strip(slug, slug_separator)
        slug = '%s%s' % (slug, end)
        next += 1

    setattr(instance, slug_field.attname, slug)


def _slug_strip(value, separator='-'):
    """
    Cleans up a slug by removing slug separator characters that occur at the
    beginning or end of a slug.

    If an alternate separator is used, it will also replace any instances of
    the default '-' separator with the new separator.
    """
    separator = separator or ''
    if separator == '-' or not separator:
        re_sep = '-'
    else:
        re_sep = '(?:-|%s)' % re.escape(separator)
    # Remove multiple instances and if an alternate separator is provided,
    # replace the default '-' separator.
    if separator != re_sep:
        value = re.sub('%s+' % re_sep, separator, value)
    # Remove separator from the beginning and end of the slug.
    if separator:
        if separator != '-':
            re_sep = re.escape(separator)
        value = re.sub(r'^%s+|%s+$' % (re_sep, re_sep), '', value)
    return value

projects/models.py
from django.db import models

# Create your models here.

homepage/forms.py
from django import forms

class ContactForm(forms.Form):
    contact_name = forms.CharField(
        required=True,
        label='Name',
    )
    contact_email = forms.EmailField(
        required=True,
        label='Email',
    )
    content = forms.CharField(
        required=True,
        label='Message',
        widget=forms.Textarea(attrs={'rows': 4}),
    )

    def __init__(self, *args, **kwargs):
        """Remove colon suffixes from labels."""
        kwargs.setdefault('label_suffix', '')
        super(ContactForm, self).__init__(*args, **kwargs)

blog/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views import generic

from .models import Post

def index(request):
    return render(request, 'blog/index.html')

def post_list(request):
    posts = Post.objects.all()
    context = { 'posts': posts }
    return render(request, 'blog/post_list.html', context=context)

class PostView(generic.DetailView):
    model = Post

homepage/views.py
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template import Context
from django.template.loader import get_template

from .forms import ContactForm
from personal_site import secret_settings

def index(request):
    """Return the landing page template."""
    # Include email contact form
    form = ContactForm()
    return render(request, 'homepage/index.html', {'form': form})

def bio(request):
    return render(request, 'homepage/bio.html')


def send_email(request):
    """
    View that sends an email to site's admin. Returns a message in response,
    indicating successfulness.
    """
    # Send email on form POST requests
    if request.method == 'POST':
        form = ContactForm(data=request.POST)

        # Process the email if good
        if form.is_valid():
            contact_name = request.POST.get('contact_name', '')
            contact_email = request.POST.get('contact_email', '')
            form_content = request.POST.get('content', '')

            template = get_template('contact_template.txt')
            context = {
                'contact_name': contact_name,
                'contact_email': contact_email,
                'form_content': form_content,
            }

            content = template.render(context)

            email = EmailMessage(
                'New contact form submission',
                content,
                'Personal site' + '',
                [secret_settings.PERSONAL_EMAIL],
                headers = {'Reply-To': contact_email},
            )
            email.send()
            message = 'Email successfully sent.'
            status = 200

        # Form wasn't valid
        else:
            message = 'There was an issue with the form submission. Please try again.'
            status = 400

    # Non-POST requests
    else:
        message = 'It looks like the request was submitted incorrectly. Note that only POST requests are valid for this URL.'
        status = 405

    return HttpResponse(message, status=status)

projects/views.py
from django.shortcuts import render

def splash_page(request):
    return render(request, 'projects/splash.html')

blog/templates/blog/base_blog.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static "homepage/css/styles.css" %}" type="text/css" />
<link rel="stylesheet" href="{% static "blog/css/blog-styles.css" %}" type="text/css" />
<link rel="stylesheet" href="{% static "styles/atom-one-dark.css" %}" type="text/css" />
{% endblock %}


{% block scripts %}
<script type="text/javascript" src="{% static "homepage/js/fractal.js" %}"></script>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "./base_blog.html" %}
{% load static %}

{% block content %}
<body>
    <div class="foreground-container">
        <div class="post-container">
            <h1 class="post-title">{{ post.title|safe }}</h1>

            <!-- Wrap content to allow whitespace  -->
            <div class="post-content">{{ post.text|safe }}</p>
                <p class="post-date">
                    Created {{ post.created_date|date:"F d, Y" }}
                </p>
            </div>
            <p>
                <a href="{% url 'blog:post_list' %}">Back to post list.</a>
            </p>
        </div>
    </div>
</body>
{% endblock %}

{% block scripts %}
{% endblock %}

blog/templates/blog/post_list.html
{% extends "./base_blog.html" %}
{% load static %}

{% block content %}
<body>
    <div class="foreground-container">
        <h1 class="blog-title">Articles</h1>
        {% for post in posts %}
        <div class="blog-listing">
            <h3><a href="{% url 'blog:post' slug=post.slug %}">{{ post.title | safe }}</a></h3>
            <p>{{ post.short_description | safe }}</p>
            <p class="post-date">{{ post.created_date|date:"F d, Y" }}</p>
        </div>
        {% endfor %}
    </div>
</body>
{% endblock %}

{% block scripts %}
{% endblock %}

homepage/templates/homepage/bio.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static "homepage/css/styles.css" %}" type="text/css" />
<link rel="stylesheet" href="{% static "homepage/css/bio-styles.css" %}" type="text/css" />
{% endblock %}

{% block content %}
<body>
    <div id="foreground-container">
        <div id="blurb">
            <p>
                I'm a developer with a love of learning new technologies, both in front-end user interfaces and back-end server-side programming. I like the occasional ping-pong and percussion, too.
            </p>
            <p>
                I started writing code when I was 8 years old, with a book of Smalltalk from my dad.  <a href="https://en.wikipedia.org/wiki/Turtle_graphics">Seeing that turtle fly across the screen</a>, controlled by abstract patterns of numbers and text, sparked something in me. The infinite possibilities stretched out before me like a computational buffet.
            </p>
            <p>
                The dishes haven't run out yet.
            </p>
        </div>
    </div>

    <!-- <canvas id="canvas2" class="fractal-canvas active" ></canvas>
    <canvas id="canvas1" class="fractal-canvas active" ></canvas> -->
</body>
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{% static "homepage/js/fractal.js" %}"></script>
<script>drawBioFractals();</script>
{% endblock %}

homepage/templates/homepage/index.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="import" href="{% static "webcomponents/awesome-button-master/awesome-button.html" %}">
<link rel="stylesheet" href="{% static "homepage/css/styles.css" %}" type="text/css" />
{% endblock %}

{% block content %}
<body>
    <div class="entry-content">
        <div class="section first-slide">
            <div class="content-wrapper">
                <div class="text-overlay">
                    <h2 class="slide-title">Hi, my name is Nathan.</h2>
                    <p>
                        I enjoy creating web sites and working with the full stack of web development.
                    </p>
                    <p>
                        <a href="#contact">Contact me</a> if you'd like to collaborate on something, or feel free to check out some <a href="#projects">projects</a> I've been working on.

                    </p>
                </div>
            </div>
        </div>

        <div class="section second-slide">
            <div class="content-wrapper">
                <h2 class="slide-title">Modern websites</h2>
                <blockquote>
                    <p>
                        The endless connections which all things have to each other is only
        hinted at here, yet the hint is enough.
                    </p>
                    <small class="quote-attribution">Douglas Hofstadter, Gödel, Escher, Bach</small>
                </blockquote>

                <p>
                    What are you looking for in a web page? Chances are, there are a few things:
                </p>
                <ul>
                    <li>A dynamic interface that goes beyond traditional media</li>
                    <li>Support for interaction between you and the reader</li>
                    <li>Seamless, natural integration of many (sometimes complex) goals</li>
                </ul>
                <p>
                    The possibilities of the web are vast, which is a large part of
                    what draws me to development. My mission is to create powerful,
                    enjoyable <em>platforms</em> that connect people and make a
                    positive impact.
                </p>
            </div>
        </div>

        <div class="section about-slide">
            <div class="content-wrapper">
                <h2 class="slide-title center">Technologies</h2>
                <div class="list-wrapper">
                    <div class="technology-category">
                        <h3>Front end</h3>
                        <ul>
                            <li>Responsive CSS</li>
                            <li>JavaScript</li>
                            <li>jQuery</li>
                            <li>AngularJS</li>
                        </ul>
                    </div>
                    <div class="technology-category">
                        <h3>Back end</h3>
                        <ul>
                            <li>Django</li>
                            <li>Python</li>
                            <li>RESTful APIs</li>
                            <li>NodeJS</li>
                            <li>SQL</li>
                        </ul>
                    </div>
                    <div class="technology-category">
                        <h3>Tools</h3>
                        <ul>
                            <li>Git</li>
                            <li>Babel</li>
                            <li>Apache</li>
                            <li>Functional programming</li>
                            <li>Object-oriented programming</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <!-- Projects slide -->
        <div id="projects" class="section projects-slide">
            <div class="content-wrapper">
                <h2 class="slide-title center">Recent projects</h2>

                <div class="project">
                    <div class="project-description">
                        <h3>My Local Market</h3>
                        <a class="code-link" title="Source on GitHub" href="https://github.com/kokopelli314/mylocalmarket">
                                &lt;Source code/&gt;</a>
                        <p>A tool to search for and save farmers markets in any zip code.</p>
                        <ul class="tags">
                            <li>Django</li>
                            <li>jQuery</li>
                            <li>Customized user profiles</li>
                            <li>Leaflet</li>
                        </ul>
                    </div>
                    <!-- <a class="img-link" href="https://nathanclonts.com/mylocalmarket/"> -->
                        <img class="project-screenshot" src="{{ MEDIA_URL }}screenshot_mylocalmarket.png" />
                    <!-- </a> -->
                </div>

                <div class="project">
                    <div class="project-description">
                        <h3>hydronote</h3>
                        <a class="code-link" title="Source on GitHub" href="https://github.com/kokopelli314/hydronote">
                                &lt;Source code/&gt;</a>
                        <p>A lightweight note-taking app in the cloud.</p>
                        <ul class="tags">
                            <li>Django</li>
                            <li>AngularJS</li>
                            <li>Django Rest Framework</li>
                            <li>tinyMCE rich text editor</li>
                        </ul>
                    </div>
                    <!-- <a class="img-link" href="https://nathanclonts.com/hydronote/"> -->
                        <img class="project-screenshot" src="{{ MEDIA_URL }}hydronote-screenshot.png" />
                    <!-- </a> -->
                </div>

		<!-- <div class="project">
                    <div class="project-description">
                        <h3><a href="https://nathanclonts.com/podcast/">Podcast site</a></h3>
                        <a class="code-link" title="Source on GitHub" href="https://github.com/kokopelli314/podcast">
                                &lt;Source code/&gt;</a>
                        <p>An interactive podcast website.</p>
                        <ul class="tags">
                            <li>Content-based site built in Django</li>
                            <li>Customized audio player</li>
                        </ul>
                    </div>
                    <a class="img-link" href="https://nathanclonts.com/podcast/">
                        <img class="project-screenshot" src="{{ MEDIA_URL }}podcast-screenshot.png" />
                    </a>
                </div> -->
            </div>
        </div>
        <!-- End of Projects slide -->

        <!-- Contact form slide  -->
        <div id="contact" class="section contact-slide">
            <div class="content-wrapper">
                <h2>Wanna chat?</h2>
                <p>
                    Want to talk about a project? Shoot me a message in the text box below and I'll get back to you soon!
                </p>

                <form id="contact-form" class="contact-form" role="form" action="send_email" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="field-wrapper">
                            {{ field.errors }}
                            {{ field.label_tag }} {{ field }}
                            {% if field.help_text %}
                                <p class="help">{{ field.help_text|safe }}</p>
                            {% endif %}
                        </div>
                    {% endfor %}

                    <div class="form-response-wrapper">
                        <p id="contact-form-message" class="form-response"></p>
                    </div>
                    <!-- <button type="submit">Send</button> -->
                    <awesome-button id="contact-form-submit" type="submit" color="green">Send</awesome-button>
                </form>
            </div>
        </div>
    </div>

</body>
{% endblock %}

{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/0.7.3/webcomponents.min.js"></script>
<script src="{% static "homepage/js/forms.js" %}" type="text/javascript"></script>
{% endblock %}

projects/templates/projects/splash.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static "projects/css/styles.css" %}" type="text/css" />
{% endblock %}

{% block content %}
<div id="current-projects">
    <h1 id="current-project-title">Current projects</h3>
    <div class="project">
        <h3><a href="https://nathanclonts.com/hydronote/">hydronote</a></h3>
        <p>a lightweight note-taking app in the cloud</p>
        <ul class="tags">
            <li>Django</li>
            <li>AngularJS</li>
            <li>Django Rest Framework</li>
            <li>tinyMCE rich text editor</li>
        </ul>
        <a href="https://nathanclonts.com/hydronote/">
            <img class="project-screenshot" src="{{ MEDIA_URL }}hydronote-screenshot.png" />
        </a>
    </div>
    <div class="project">
        <h3><a href="https://nathanclonts.com/podcast/">Podcast site</a></h3>
        <p>an interactive podcast website</p>
        <ul class="tags">
            <li>Django</li>
            <li>Customized audio player</li>
        </ul>
        <a href="https://nathanclonts.com/podcast/">
            <img class="project-screenshot" src="{{ MEDIA_URL }}podcast-screenshot.png" />
        </a>
    </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en-US">
    <head>
        <!-- Meta       -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="I help businesses by developing custom web applications, system integrations, and providing software support.">

        <!-- Favicons       -->
        <link rel="icon" type="image/png" sizes="32x32"
              href="{{MEDIA_URL}}favicons/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="96x96"
              href="{{MEDIA_URL}}favicons/favicon-96x96.png">
        <link rel="icon" type="image/png" sizes="16x16"
              href="{{MEDIA_URL}}favicons/favicon-16x16.png">

        <!-- Beginning of content       -->
        {% block title %}<title>Nathan Clonts</title>{% endblock %}

        <link rel="stylesheet" href="{% static "css/hamburgers.css" %}" type="text/css" />
        <link rel="stylesheet" href="{% static "css/base-styles.css" %}" type="text/css" />
        {% block stylesheets %}{% endblock %}

	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-104777835-1"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-104777835-1');
	</script>
    </head>

    <body>
        <!-- Actual slide-in menu -->
        <nav class="menu hidden">
            <a href="{% url 'homepage:index' %}" class="menu-link">
                <span>about</span>
            </a>
            <a href="{% url 'blog:post_list' %}" class="menu-link">
                <span>blog</span>
            </a>
            <a href="{% url 'homepage:index' %}#contact" class="menu-link">
                <span>contact</span>
            </a>
        </nav>

        <!-- Hamburger menu button -->
        <button class="hamburger hamburger--vortex" type="button">
            <span class="hamburger-box">
                <span class="hamburger-inner"></span>
            </span>
        </button>

        <div class="page-content">
            {% block content %}
            {% endblock %}
        </div>


        <!-- Footer -->
        <footer>
            <div class="content-wrapper">
                <div>
                    <p>Site by Nathan Clonts © {% now "Y" %} </p>
                    <p>Fort Collins, Colorado</p>
                </div>

                <div class="social-links">
                  <p>
                    <a href="https://github.com/naclonts" target="_blank">GitHub</a> |
                    <a href="https://www.linkedin.com/in/nathan-clonts-a94711b6/" target="_blank">LinkedIn</a>
                  <p>
                  <p></p>
                </div>
                {% block footer-bottom %}
                {% endblock %}
            </div>
        </footer>
    </body>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="{% static "dist/main.js" %}" type="text/javascript" ></script>
    {% block scripts %}
    {% endblock %}
</html>

templates/contact.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static "css/contact.css" %}" type="text/css" />
{% endblock %}

{% block content %}
<div class="bg-container">
    <div class="contact-info">
        <h1>Contact</h1>
        <p>
            Want to talk about a project? Shoot me a message in the text box below and I'll get back to you soon!
        </p>

        <form class="contact-form" role="form" action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Send</button>
        </form>
    </div>
</div>
{% endblock %}